Avoid crashing when global search encounters a NoClassDefFoundError
(cherry picked from commit 9c426bc216d2ca61dd1168f119b4ddc99e770e47)
(cherry picked from commit 8a32db268ec4b83737b232bf55e4c1da2ad5cbb9)